### ISSUE TITLE
/usr/local/ 以下のPATHについて

### ISSUE THREAD

**Issue by forno** [YamaCIR-KIT/utilib#1]
デフォルトで/usr/local/以下のlibrary, include ディレクトリにはpathが通っているはず。

/usr/local/に展開するのではなく
共有ライブラリと静的ライブラリは /usr/local/lib/ へ
inlcudeファイルは /usr/local/includeへ
管理者権限で、かつpermissionを644にして書き込んでみてはいかがでしょう。

**Comment by forno** [comment]
わかったうえで避けてるのか。 でもInstallするならpathが通ってそうなところにすればいいと思う。

path通らないところに置くなら手動でインストしてろって意見です。

**Comment by forno** [comment]
ついでにいえば includeの方はディレクトリネストしても大丈夫です。

**Comment by forno** [comment]
あれからいろいろと調べまわった結論からいうと、

1. /usr/local 以外のパスが通ってるところはパッケージ管理システムが触ってる可能性があるので触るな _※/usrもだめです_
2. /usr/local か /opt はシステム周りでつついていい
3. /usr/local はFHS準拠なので勝手にネストすることはできない
4. /opt はFHS準拠じゃないから好き勝手作れるけど別にPATH通ってねぇから

てな感じです。
ちなみに、includeはFHS的にディレクトリ作れるけどパス通すなら `#include <dir/file.h>`になる

分かってると思うけどコンパイラのincludeは `/usr/include:/usr/local/include` とかから引っ張ってくるし
リンカは `/lib:/usr/lib:/usr/local/lib` とかから引っ張ってくる。

確認方法についてはしたことはあるはずだがやり方は忘れた。

**Comment by YamaCIR-KIT** [comment]
全部知ってる
魔導書で確認済み
/usr/ 触っちゃいけないなんてルールは無いはずだぞ

**Comment by forno** [comment]
ルールはないが別にパッケージ管理システムに除外されても知らねってスタンスじゃね？

**Comment by forno** [comment]
まあ、じゃあ聞くけど、純粋になにを思ってlibの下にディレクトリを作って放り込むんだぜ？

**Comment by YamaCIR-KIT** [comment]
パッケージ管理システムってpkg-configの事だよな
まさかaptの話じゃないだろ？

**Comment by YamaCIR-KIT** [comment]
パス通すのも/etc/ld.so.conf弄るだけってのは知ってるけど，readmeに書いてあるのは出てきたエラーがCMakeListsの書き方がおかしいのかconfig.cmakeがおかしいのかよく分からんからとりあえずパスだけは確実に通るだろう/usrにしようかって話よ

**Comment by forno** [comment]
あー。つまり、なんのパスを通したいんだ？

**Comment by YamaCIR-KIT** [comment]
libの下にディレクトリがあるのは俺のミス

**Comment by YamaCIR-KIT** [comment]
というかパス云々の問題は一昨日には解決しててだな

**Comment by forno** [comment]
まじかよ。どう解決したかをカキコしつつIssue閉じておいて(赤面

**Comment by YamaCIR-KIT** [comment]
結論から言うとパスは最初から通ってた
ずっと悩んでたのはこのutilibを使うときにutilibが依存してるライブラリの依存が上手く引き継げないこと
それがパスの問題かと疑ってたがそんなことはなかった
もちろん丁寧にCMakeLists書けば当然通るわけだけど，多分CMakeの知識が足りてないだけでちゃんと出来るはず
